create database if no exists conquest_go

create table usuarios(
	id int auto_increment primary key,
    nome varchar(200) not null,
    email varchar(200) not null,
    telefone varchar(200) not null,
    senha varchar(200) not null,
    nivel_acessos enum('usuario','autor','Administrador')
    );
    create table ImagemPerfil(
    id_PhotoPerfil int auto_increment primary key,
    FotoPerfil longblob not null,
    id_user int,
    foreign key (id_user) references usuarios(id)
    );
    create table Postagens(
     id_postagem int auto_increment primary key,
     titulo varchar(200) not null,
     imagem longblob not null,
     descricao varchar(200) not null,
     categoria varchar(200) not null,
     id_autor int,
     foreign key (id_autor) references usuarios(id)
    );
    create table TermosDeServico
    (
    id_TermosDeServico int auto_increment primary key,
    aceitacao_de_Termos boolean,
    id_usuario int,
    foreign key (id_usuario) references usuarios(id)
    );
    
    /** Prevenção de Erros **/
    
/** drop table ImagemPerfil; **/
/** drop table Postagens;
/** drop table TermosDeServico;
/**drop table usuarios; **/
insert into usuarios (nome,email,telefone,senha,nivel_acessos) values ('Anderson Pires','andersonpiresdacruz@gmail.com','(61) 98319-8438','Ander062','Administrador');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Alice Silva', 'alice.silva@example.com', '(11) 98765-4321', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bob Oliveira', 'bob.oliveira@example.com', '(22) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Charlie Santos', 'charlie.santos@example.com', '(33) 76543-2109', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('David Pereira', 'david.pereira@example.com', '(44) 65432-1098', 'senha987', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Eva Almeida', 'eva.almeida@example.com', '(55) 54321-0987', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Carlos Lima', 'carlos.lima@example.com', '(66) 43210-9876', 'senha321', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fernanda Rocha', 'fernanda.rocha@example.com', '(77) 32109-8765', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gustavo Mendes', 'gustavo.mendes@example.com', '(88) 21098-7654', 'senha987', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Helena Pereira', 'helena.pereira@example.com', '(99) 10987-6543', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isaac Souza', 'isaac.souza@example.com', '(10) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Juliana Costa', 'juliana.costa@example.com', '(21) 12345-6789', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(32) 98765-4321', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(43) 87654-3210', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(87) 43210-9876', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(98) 32109-8765', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(43) 21098-7654', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(54) 10987-6543', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(65) 87654-3210', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(43) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(54) 10987-6543', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(65) 87654-3210', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(76) 76543-2109', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(87) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(98) 54321-0987', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(09) 43210-9876', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(10) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(21) 21098-7654', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(32) 10987-6543', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(43) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(54) 76543-2109', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(65) 65432-1098', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(76) 54321-0987', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(87) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(98) 32109-8765', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(09) 21098-7654', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(10) 10987-6543', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(21) 87654-3210', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(32) 76543-2109', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(43) 65432-1098', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(54) 54321-0987', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(65) 43210-9876', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(76) 32109-8765', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(87) 21098-7654', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(98) 10987-6543', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(09) 87654-3210', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(10) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(21) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(32) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(43) 43210-9876', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(54) 32109-8765', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(65) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(76) 10987-6543', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(87) 87654-3210', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(98) 76543-2109', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(09) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(10) 54321-0987', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(21) 43210-9876', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(32) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(43) 21098-7654', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(54) 10987-6543', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(65) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(76) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(87) 54321-0987', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(98) 43210-9876', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(09) 32109-8765', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(10) 21098-7654', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Alice Silva', 'alice.silva@example.com', '(11) 98765-4321', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bob Oliveira', 'bob.oliveira@example.com', '(22) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Charlie Santos', 'charlie.santos@example.com', '(33) 76543-2109', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('David Pereira', 'david.pereira@example.com', '(44) 65432-1098', 'senha987', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Eva Almeida', 'eva.almeida@example.com', '(55) 54321-0987', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Carlos Lima', 'carlos.lima@example.com', '(66) 43210-9876', 'senha321', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fernanda Rocha', 'fernanda.rocha@example.com', '(77) 32109-8765', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gustavo Mendes', 'gustavo.mendes@example.com', '(88) 21098-7654', 'senha987', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Helena Pereira', 'helena.pereira@example.com', '(99) 10987-6543', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isaac Souza', 'isaac.souza@example.com', '(10) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Juliana Costa', 'juliana.costa@example.com', '(21) 12345-6789', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(32) 98765-4321', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(43) 87654-3210', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(87) 43210-9876', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(98) 32109-8765', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(43) 21098-7654', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(54) 10987-6543', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(65) 87654-3210', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(43) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(54) 10987-6543', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(65) 87654-3210', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(76) 76543-2109', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(87) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(98) 54321-0987', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(09) 43210-9876', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(10) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(21) 21098-7654', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(32) 10987-6543', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(43) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(54) 76543-2109', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(65) 65432-1098', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(76) 54321-0987', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(87) 43210-9876', 'senha789','usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Alice Silva', 'alice.silva@example.com', '(11) 98765-4321', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bob Oliveira', 'bob.oliveira@example.com', '(22) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Charlie Santos', 'charlie.santos@example.com', '(33) 76543-2109', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('David Pereira', 'david.pereira@example.com', '(44) 65432-1098', 'senha987', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Eva Almeida', 'eva.almeida@example.com', '(55) 54321-0987', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Carlos Lima', 'carlos.lima@example.com', '(66) 43210-9876', 'senha321', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fernanda Rocha', 'fernanda.rocha@example.com', '(77) 32109-8765', 'senha654', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gustavo Mendes', 'gustavo.mendes@example.com', '(88) 21098-7654', 'senha987', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Helena Pereira', 'helena.pereira@example.com', '(99) 10987-6543', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isaac Souza', 'isaac.souza@example.com', '(10) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Juliana Costa', 'juliana.costa@example.com', '(21) 12345-6789', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(32) 98765-4321', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(43) 87654-3210', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(87) 43210-9876', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(98) 32109-8765', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(43) 21098-7654', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(54) 10987-6543', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(65) 87654-3210', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(09) 65432-1098', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(10) 54321-0987', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(21) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(32) 32109-8765', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(43) 21098-7654', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(54) 10987-6543', 'senha890', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(65) 87654-3210', 'senha123', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(76) 76543-2109', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(87) 65432-1098', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(98) 54321-0987', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(09) 43210-9876', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(10) 32109-8765', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(21) 21098-7654', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(32) 10987-6543', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(43) 87654-3210', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(54) 76543-2109', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(65) 65432-1098', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(76) 54321-0987', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(87) 43210-9876', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(98) 21098-7654', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(09) 10987-6543', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(10) 87654-3210', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(21) 76543-2109', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(32) 65432-1098', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(43) 54321-0987', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(54) 43210-9876', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(65) 32109-8765', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(76) 21098-7654', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(87) 10987-6543', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(98) 87654-3210', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(09) 76543-2109', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(10) 65432-1098', 'senha678', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(21) 54321-0987', 'senha901', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(32) 43210-9876', 'senha234', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(43) 32109-8765', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(54) 21098-7654', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(65) 10987-6543', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(76) 87654-3210', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(87) 76543-2109', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(98) 65432-1098', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(09) 54321-0987', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(10) 43210-9876', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(21) 32109-8765', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(32) 21098-7654', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(43) 10987-6543', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(54) 87654-3210', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(65) 76543-2109', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(76) 65432-1098', 'senha456', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(87) 54321-0987', 'senha789', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(98) 43210-9876', 'senha012', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(09) 32109-8765', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(10) 21098-7654', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(21) 10987-6543', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(32) 87654-3210', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(43) 76543-2109', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(54) 65432-1098', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(65) 54321-0987', 'senha123', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(76) 43210-9876', 'senha456', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(87) 32109-8765', 'senha789', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(98) 21098-7654', 'senha012', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(09) 10987-6543', 'senha345', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(10) 87654-3210', 'senha678', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(21) 76543-2109', 'senha901', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(32) 65432-1098', 'senha234', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(43) 54321-0987', 'senha567', 'usuario');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(54) 43210-9876', 'senha890', 'autor');
INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(65) 65432-1098', 'senha901', 'autor')


-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Alice Silva', 'alice.silva@example.com', '(11) 98765-4321', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bob Oliveira', 'bob.oliveira@example.com', '(22) 87654-3210', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Charlie Santos', 'charlie.santos@example.com', '(33) 76543-2109', 'senha789', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('David Pereira', 'david.pereira@example.com', '(44) 65432-1098', 'senha987', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Eva Almeida', 'eva.almeida@example.com', '(55) 54321-0987', 'senha654', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Carlos Lima', 'carlos.lima@example.com', '(66) 43210-9876', 'senha321', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fernanda Rocha', 'fernanda.rocha@example.com', '(77) 32109-8765', 'senha654', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gustavo Mendes', 'gustavo.mendes@example.com', '(88) 21098-7654', 'senha987', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Helena Pereira', 'helena.pereira@example.com', '(99) 10987-6543', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isaac Souza', 'isaac.souza@example.com', '(10) 87654-3210', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Juliana Costa', 'juliana.costa@example.com', '(21) 12345-6789', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(32) 98765-4321', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(43) 87654-3210', 'senha345', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(54) 76543-2109', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(65) 65432-1098', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(76) 54321-0987', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(87) 43210-9876', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(98) 32109-8765', 'senha890', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(09) 21098-7654', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(10) 10987-6543', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(21) 87654-3210', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(32) 76543-2109', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(43) 65432-1098', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(54) 54321-0987', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(65) 43210-9876', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(76) 32109-8765', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(87) 21098-7654', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(98) 10987-6543', 'senha890', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(09) 87654-3210', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(10) 76543-2109', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(21) 65432-1098', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(32) 54321-0987', 'senha012', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(43) 43210-9876', 'senha345', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(65) 21098-7654', 'senha901', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(76) 10987-6543', 'senha234', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(87) 87654-3210', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(98) 76543-2109', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(09) 65432-1098', 'senha123', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(10) 54321-0987', 'senha456', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(21) 43210-9876', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(32) 32109-8765', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(43) 21098-7654', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(54) 10987-6543', 'senha678', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(65) 87654-3210', 'senha901', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(09) 65432-1098', 'senha123', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(10) 54321-0987', 'senha456', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(21) 43210-9876', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(32) 32109-8765', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(43) 21098-7654', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(54) 10987-6543', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(65) 87654-3210', 'senha123', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(76) 76543-2109', 'senha456', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(87) 65432-1098', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(98) 54321-0987', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(09) 43210-9876', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(10) 32109-8765', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(21) 21098-7654', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(32) 10987-6543', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(43) 87654-3210', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(54) 76543-2109', 'senha890', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(65) 65432-1098', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(76) 54321-0987', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(87) 43210-9876', 'senha789','usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(76) 76543-2109', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(87) 65432-1098', 'senha567', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(98) 54321-0987', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(09) 43210-9876', 'senha123', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(10) 32109-8765', 'senha456', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(21) 21098-7654', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(32) 10987-6543', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ana Costa', 'ana.costa@example.com', '(43) 87654-3210', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Bruno Oliveira', 'bruno.oliveira@example.com', '(54) 76543-2109', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Clara Lima', 'clara.lima@example.com', '(65) 65432-1098', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Daniel Silva', 'daniel.silva@example.com', '(76) 54321-0987', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Elisa Santos', 'elisa.santos@example.com', '(87) 43210-9876', 'senha567', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Fábio Rocha', 'fabio.rocha@example.com', '(98) 32109-8765', 'senha890', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Gabriela Mendes', 'gabriela.mendes@example.com', '(09) 21098-7654', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Hugo Pereira', 'hugo.pereira@example.com', '(10) 10987-6543', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Isabela Souza', 'isabela.souza@example.com', '(21) 87654-3210', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('João Almeida', 'joao.almeida@example.com', '(32) 76543-2109', 'senha012', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Karen Lima', 'karen.lima@example.com', '(43) 65432-1098', 'senha345', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Lucas Oliveira', 'lucas.oliveira@example.com', '(54) 54321-0987', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Mariana Lima', 'mariana.lima@example.com', '(65) 43210-9876', 'senha901', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Natan Silva', 'natan.silva@example.com', '(76) 32109-8765', 'senha234', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Olivia Santos', 'olivia.santos@example.com', '(87) 21098-7654', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Pedro Rocha', 'pedro.rocha@example.com', '(98) 10987-6543', 'senha890', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Quiteria Mendes', 'quiteria.mendes@example.com', '(09) 87654-3210', 'senha123', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ricardo Pereira', 'ricardo.pereira@example.com', '(10) 76543-2109', 'senha456', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Sofia Souza', 'sofia.souza@example.com', '(21) 65432-1098', 'senha789', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Tiago Almeida', 'tiago.almeida@example.com', '(32) 54321-0987', 'senha012', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Ursula Lima', 'ursula.lima@example.com', '(43) 43210-9876', 'senha345', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Vinicius Oliveira', 'vinicius.oliveira@example.com', '(54) 32109-8765', 'senha678', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Wanessa Santos', 'wanessa.santos@example.com', '(65) 21098-7654', 'senha901', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Xavier Silva', 'xavier.silva@example.com', '(76) 10987-6543', 'senha234', 'autor');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Yara Rocha', 'yara.rocha@example.com', '(87) 87654-3210', 'senha567', 'usuario');
-- INSERT INTO usuarios (nome,email,telefone,senha,nivel_acessos) VALUES('Zé Mendes', 'ze.mendes@example.com', '(98) 76543-2109', 'senha890', 'usuario');
